FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive

# necessary arguments
ARG user
ARG group=${user}

# add user for convenient working with host files
RUN useradd -mUs /bin/bash ${user} && \
    usermod -aG sudo ${user} && \
    usermod -aG dialout ${user} && \
    echo "${user} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN apt update \
 && \
 apt install -y \
 cmake \
 g++ \
 gcc \
 gdb \
 qt5-default

RUN apt install -y libcppunit-dev

USER ${user}