MultipleMSView:
  scale: 1.05
  GlobalOptions:
    initial_time:
      default: 0
      value: 0
      description: initial time instant used in simulation
      units: seconds
    final_time:
      default: 1
      value: 1
      description: final time instant used in simulation
      units: seconds
    delta_time:
      default: 0.01
      value: 0.02
      description: time step used in simulation
      units: seconds
  # workspaces:
  #   MultipleMSView:
  #     MSOptions:
  #       RBOptions:

